name: example
description: Example for how to use an ImplicitlyAnimatedReorderableList
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  animated_list_plus:
    path: ../
  flutter:
    sdk: flutter
  flutter_slidable: ^0.6.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
